# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- docker-compose.yml
- Gemfile
- Gemfile.lock
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: posts/page:num # jekyll-paginate > blog page

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: umbracaesarea # jekyll-seo-tag > Owners twitter username

author: E B # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: E B # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/umbracaesarea
    - https://www.linkedin.com/in/enoc-balderas-23b394140/
    - https://github.com/PontifexGnosis1729
    - "mailto:rundown.disused_8y@icloud.com"

# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
remote_theme: daviddarnes/alembic@main
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Chicago # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: "Posts" # Needed for Siteleaf
    output: true
    permalink: /:collection/:title
    feature_text: "# The Beyond (fast zone)"
    feature_image: "https://pbs.twimg.com/media/GfRtnudbMAAwxSI?format=jpg&name=4096x4096"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "https://pbs.twimg.com/media/GfRtnudbMAAwxSI?format=jpg&name=4096x4096"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "The Beyond (fast zone)" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "We're working on AI tools to escape the slow zone. Here's how you can connect with us:" # Site description and default description, also used in jekyll-seo-tag
short_name: "FTL" # The web application short name, defaults to the site title
url: "https://pontifexgnosis1729.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "rundown.disused_8y@icloud.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account

date_format: "%B %d, %Y" # Blog post date formatting using placeholder formatting
service_worker: true # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

google_analytics: "G-316TN36SP0"
google_analytics_anonymize_ip: false

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Writings
  url: /posts/
#- title: Tech
#  url: /tools/
- title: About
  url: /about/

navigation_footer:
- title: Galts Gulch
  url: https://www.hope.com/
- title: About
  url: /about/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/umbracaesarea
  LinkedIn: https://www.linkedin.com/in/enoc-balderas-23b394140/
  GitHub: https://github.com/PontifexGnosis1729
  email: "mailto:rundown.disused_8y@icloud.com"
  RSS: /feed.xml

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
