services:
  jekyll:
    image: tiryoh/jekyll:latest
    container_name: my-jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    command: jekyll serve --host 0.0.0.0 --watch
